######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 19 18:39:41 2015
######################################################################

TEMPLATE = lib
TARGET = mykeydriverplugin
CONFIG +=plugin
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mykey_global.h mykeydriverplugin.h qkbdmy_qws.h
SOURCES += mykeydriverplugin.cpp qkbdmy_qws.cpp
